In [4]:
tinggi = [51, 72, 64, 87, 90]
lebar = [100, 201, 51, 12, 12]


tinggi * lebar

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
import numpy as np

In [8]:
arr_tinggi = np.array(tinggi)
arr_lebar = np.array(lebar)
arr_panjang = np.array([10, 20, 30, 40, 50])

hasil = arr_tinggi * arr_lebar * arr_panjang * arr_tinggi
print(hasil, type(hasil))

[ 2601000 20839680  6266880  3633120  4860000] <class 'numpy.ndarray'>


In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.empty(4)

array([2.12199579e-314, 4.47593775e-091, 4.13038880e-321, 3.79442416e-321])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr_numbers = np.arange(7, 15, 2)
arr_numbers

array([ 7,  9, 11, 13])

In [19]:
arr_numbers = np.append(arr_numbers, 15)
arr_numbers

array([ 7,  9, 11, 13, 15])

In [20]:
hasil = np.append(arr_numbers, [15, 17])
print(hasil)
print(type(hasil))

[ 7  9 11 13 15 15 17]
<class 'numpy.ndarray'>


In [21]:
tempel2list = np.append([1, 2, 3],[4, 5, 6])
print(type(tempel2list))

<class 'numpy.ndarray'>


In [25]:
hasil_return = np.delete(tempel2list,1)
print(hasil_return)

[1 3 4 5 6]


In [26]:
random_numbers = np.array([-1, 1, 5, -5, -6, 6, 0, 0])
np.sort(random_numbers)

array([-6, -5, -1,  0,  0,  1,  5,  6])

In [27]:
random_numbers

array([-1,  1,  5, -5, -6,  6,  0,  0])

In [28]:
random_numbers.ndim

1

In [31]:
arr_2d = np.array([
    ["o","x","o"],
    ["x","x","o"],
    ["o"," "," "],
])

In [32]:
arr_2d.ndim

2

In [34]:
random_numbers.size

8

In [35]:
random_numbers.shape

(8,)

In [38]:
transposed = arr_2d.reshape(3,3)
transposed.shape
print(arr_2d)
print(transposed)

[['o' 'x' 'o']
 ['x' 'x' 'o']
 ['o' ' ' ' ']]
[['o' 'x' 'o']
 ['x' 'x' 'o']
 ['o' ' ' ' ']]


In [45]:
arr_nums_baru = random_numbers[np.newaxis]
arr_nums_baru

array([[-1,  1,  5, -5, -6,  6,  0,  0]])

In [49]:
random_numbers[np.newaxis, :]

array([[-1,  1,  5, -5, -6,  6,  0,  0]])

In [50]:
random_numbers[:, np.newaxis]

array([[-1],
       [ 1],
       [ 5],
       [-5],
       [-6],
       [ 6],
       [ 0],
       [ 0]])

In [51]:
np.expand_dims(random_numbers, axis=0)

array([[-1,  1,  5, -5, -6,  6,  0,  0]])

In [53]:
np.expand_dims(random_numbers, axis=1)

array([[-1],
       [ 1],
       [ 5],
       [-5],
       [-6],
       [ 6],
       [ 0],
       [ 0]])

In [54]:
random_numbers[-3:]

array([6, 0, 0])

In [55]:
random_numbers[1:3]

array([1, 5])

In [56]:
random_numbers[random_numbers < 0 ]

array([-1, -5, -6])

In [58]:
random_numbers[random_numbers % 2 == 1]

array([-1,  1,  5, -5])

In [64]:
arr_a = np.array([[1,2], [3,4]])
arr_a

array([[1, 2],
       [3, 4]])

In [61]:
arr_b = np.array([[5,6],[7,8]])
arr_b

array([[5, 6],
       [7, 8]])

In [66]:
np.vstack((arr_a, arr_b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
h_arr = np.hstack((arr_a, arr_b))
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [70]:
hasil = np.hsplit(h_arr,4)
print(hasil)
print(type(hasil))

[array([[1],
       [3]]), array([[2],
       [4]]), array([[5],
       [7]]), array([[6],
       [8]])]
<class 'list'>


In [71]:
np.hsplit(np.zeros(12), 3)

[array([0., 0., 0., 0.]), array([0., 0., 0., 0.]), array([0., 0., 0., 0.])]

In [72]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
b = a.view()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
b = np.append(b, [20,30])
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 20 30]


In [75]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  20  30]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [76]:
c = a.copy()
c[0] = 9
print(c)
print(a)

[ 9  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [77]:
b = a.view()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [79]:
h_arr.sum(axis = 0)

array([ 4,  6, 12, 14])

In [80]:
h_arr.sum(axis = 1)

array([14, 22])

In [83]:
h_arr + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [84]:
h_arr - np.ones(8).reshape(2,4)

array([[0., 1., 4., 5.],
       [2., 3., 6., 7.]])

In [85]:
h_arr * (np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4))

array([[ 2.,  4., 10., 12.],
       [ 6.,  8., 14., 16.]])

In [87]:
h_arr / (np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4))

array([[0.5, 1. , 2.5, 3. ],
       [1.5, 2. , 3.5, 4. ]])

In [88]:
h_arr * 2

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [89]:
h_arr / 2

array([[0.5, 1. , 2.5, 3. ],
       [1.5, 2. , 3.5, 4. ]])

In [90]:
h_arr + 2

array([[ 3,  4,  7,  8],
       [ 5,  6,  9, 10]])

In [92]:
data_awal = h_arr + 3
data_awal

array([[ 4,  5,  8,  9],
       [ 6,  7, 10, 11]])

In [93]:
data_awal.min()

4

In [94]:
data_awal.max()

11

In [95]:
data_awal.sum()

60

In [96]:
data_awal.mean()

7.5

In [97]:
data_awal.std()

2.29128784747792

In [102]:
m1 = np.array([
    [1,2,3],
    [4,5,6]
])

m2 = np.array([
    [7,8],
    [9,10],
    [11,12]
])

hasil = np.dot(m1, m2)
hasil

array([[ 58,  64],
       [139, 154]])

In [104]:
hasil[0,0]

58

In [105]:
hasil[1]

array([139, 154])

In [106]:
hasil[1,1]

154

In [107]:
hasil[:,1]

array([ 64, 154])

In [108]:
hasil[-1]

array([139, 154])

In [109]:
m2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [113]:
m2.reshape(3,2)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [114]:
m2.T

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [115]:
np.zeros(3)

array([0., 0., 0.])

In [117]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [119]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [121]:
np.random.random(2)

array([0.6401429 , 0.60129726])

In [122]:
arr_3d =np.zeros((3,2,3))

In [123]:
arr_3d.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [124]:
arr_3d.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [125]:
hasil = (1/n) * np.sum(npsquare(observed - predition))

NameError: name 'n' is not defined